### ISSUE TITLE
No support for unix domain sockets?

### ISSUE THREAD

**Issue by bedge** [miguelgrinberg/Flask-Runner#7]
The --port option seems to not work for unix domain sockets, or I've got the syntax wrong, eg:
With gunicorn I'm using 

> --bind unix:ml-ingestor.sock

so I was hoping to be able to do something similar with this.

Here's the result from using `-p  unix:ml-ingestor.sock`

> usage: app.py [-h] [-t HOST] [-p PORT] [--threaded] [--processes PROCESSES]
>               [--passthrough-errors] [-d] [-r] [--noeval] [--extra FILE]
>               [--profile] [--profile-count COUNT] [--profile-percent PERCENT]
>               [--profile-regex REGEX] [--profile-dir DIR] [--lint]
> app.py: error: argument -p/--port: invalid int value: 'unix:ml-ingestor.sock'
> The program exited via sys.exit(). Exit status:  2

**Comment by miguelgrinberg** [comment]
That is not a limitation of this extension, but of the Flask development web server. If you want to run your application on a unix socket, you can use a web server that supports that, such as gunicorn.

**Comment by bedge** [comment]
I was thinking one could use this
https://github.com/tomekwojcik/werkzeug_plus_unix_sockets
to add unix socket support to a flask app directly and expose it through this runner.

The use case is this:
I usually run nginx-> unix socket -> gunicorn-> flask

But sometimes I want to start the app by hand under pdb, so I'd like to expose flask to the same unix socket that nginx is using. This lets me get at a debugger without changing anything else.

Maybe I'm going about this the wrong way and there's some mechanism for using a debugger while running under gunicorn, but I was under the impression that that wasn't possible in a pre-forking environment.

**Comment by miguelgrinberg** [comment]
The project that you linked hasn't been updated in 3 years, and it uses monkey patching to add the unix socket functionality to Werkzeug. It would make more sense to add this support directly into Werkzeug, with monkey patching it is really hard to tell for how long that project will continue to work unmaintained, if it still works at all.

Also, consider that flask now has its own runner (the `flask` command), so Flask-Runner is sort of not needed anymore, so I don't see a lot of need to put more development effort in this extension.

**Comment by bedge** [comment]
fair enough, thanks for the information.
